import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Ticket as TicketIcon, MoreVertical } from 'lucide-react';

export default function MyTickets() {
  const [activeTab, setActiveTab] = useState('Upcoming');
  const [tickets, setTickets] = useState([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchTickets = async () => {
      const token = localStorage.getItem('token');
      if (!token) {
        setLoading(false);
        return;
      }

      try {
        const API = import.meta.env.VITE_API_URL || 'http://localhost:5000';
        const res = await fetch(`${API}/api/tickets/my-tickets`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (res.ok) {
          const data = await res.json();
          setTickets(data);
        }
      } catch (err) {
        console.error("Failed to fetch tickets", err);
      } finally {
        setLoading(false);
      }
    };

    fetchTickets();
  }, []);

  return (
    <div className="page my-tickets-page">
      <div className="header">
        <h1 className="header-title">My Tickets</h1>
      </div>

      <div style={{ padding: '16px', display: 'flex', justifyContent: 'center' }}>
        <div style={{ display: 'flex', backgroundColor: '#e0e0e0', borderRadius: '8px', padding: '4px', width: '100%', maxWidth: '300px' }}>
          {['Upcoming', 'Past'].map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              style={{
                flex: 1,
                padding: '8px',
                border: 'none',
                borderRadius: '6px',
                backgroundColor: activeTab === tab ? '#fff' : 'transparent',
                fontWeight: activeTab === tab ? 600 : 500,
                color: activeTab === tab ? 'var(--text-primary)' : 'var(--text-secondary)',
                boxShadow: activeTab === tab ? '0 2px 4px rgba(0,0,0,0.1)' : 'none',
                cursor: 'pointer',
                transition: 'all 0.2s'
              }}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      <div style={{ padding: '24px 16px' }}>
        {loading ? (
          <div style={{ textAlign: 'center', padding: '40px' }}>Loading tickets...</div>
        ) : tickets.length > 0 ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            {tickets.map(ticket => (
              <div key={ticket._id} style={{ display: 'flex', flexDirection: 'column' }}>
                
                {/* Order Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
                  <h2 style={{ fontSize: '18px', fontWeight: 800 }}>Order #{ticket._id.substring(0, 8).toUpperCase()}</h2>
                  <MoreVertical size={20} color="#333" />
                </div>
                <div style={{ color: '#888', fontSize: '14px', marginBottom: '16px' }}>
                  x{ticket.seats.length} Tickets • {ticket.eventTitle}
                </div>

                {/* Individual Tickets */}
                {ticket.seats.map((seatString, idx) => {
                  // Parse the seat string generated by SeatSelection
                  let section = '-';
                  let row = '-';
                  let seat = '-';
                  let type = 'Standard Ticket';

                  if (seatString.includes('General Admission')) {
                     type = 'General Admission';
                     const secMatch = seatString.match(/Section:\s*([^,]+)/);
                     if (secMatch) section = secMatch[1].trim();

                     const tktMatch = seatString.match(/Ticket Number:\s*(\d+)/);
                     if (tktMatch) seat = tktMatch[1];
                     row = 'GA';
                  } else if (seatString.includes('Seat Number:')) {
                     type = 'Reserved Seating';
                     const secMatch = seatString.match(/Section:\s*([^,]+)/);
                     if (secMatch) section = secMatch[1].trim();
                     
                     const rowMatch = seatString.match(/Row:\s*([^,]+)/);
                     if (rowMatch) row = rowMatch[1].trim();

                     const seatMatch = seatString.match(/Seat Number:\s*(\d+)/);
                     if (seatMatch) seat = seatMatch[1];
                  } else {
                     // Fallback for older formats
                     section = seatString;
                  }

                  return (
                    <div key={idx} style={{ 
                      backgroundColor: '#fff', 
                      border: '1px solid #f0f0f0', 
                      marginBottom: '16px', 
                      borderRadius: '4px', 
                      overflow: 'hidden' 
                    }}>
                      {/* Ticket Type Bar */}
                      <div style={{ backgroundColor: '#f0f0f0', padding: '12px 16px', fontWeight: 700, fontSize: '14px', color: '#333' }}>
                        {type}
                      </div>
                      
                      {/* 3 Columns for Details */}
                      <div style={{ display: 'flex', padding: '16px' }}>
                        <div style={{ flex: 1 }}>
                          <div style={{ color: '#888', fontSize: '11px', fontWeight: 700, letterSpacing: '1px', marginBottom: '4px' }}>SECTION</div>
                          <div style={{ fontSize: '20px', fontWeight: 800 }}>{section}</div>
                        </div>
                        <div style={{ flex: 1, textAlign: 'center' }}>
                          <div style={{ color: '#888', fontSize: '11px', fontWeight: 700, letterSpacing: '1px', marginBottom: '4px' }}>ROW</div>
                          <div style={{ fontSize: '20px', fontWeight: 800 }}>{row}</div>
                        </div>
                        <div style={{ flex: 1, textAlign: 'right' }}>
                          <div style={{ color: '#888', fontSize: '11px', fontWeight: 700, letterSpacing: '1px', marginBottom: '4px' }}>SEAT</div>
                          <div style={{ fontSize: '20px', fontWeight: 800 }}>{seat}</div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            ))}
          </div>
        ) : (
          <div style={{ textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', marginTop: '24px' }}>
            <div style={{ marginBottom: '24px', padding: '24px', backgroundColor: '#fff', borderRadius: '50%', display: 'inline-block', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}>
              <TicketIcon size={48} color="var(--primary-color)" />
            </div>
            
            <h2 style={{ fontSize: '20px', fontWeight: 700, marginBottom: '12px' }}>
              No {activeTab.toLowerCase()} tickets
            </h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '32px', lineHeight: 1.5 }}>
              When you buy tickets, they will show up here.
            </p>
            
            <button className="btn-primary" style={{ maxWidth: '200px' }} onClick={() => navigate('/')}>Find Tickets</button>
          </div>
        )}
      </div>
    </div>
  );
}
